feat: Add Trivy to ADOPT
extenda/tech-radar pull request #196
Opened 2021-01-19 10:05 UTC by askoriy

2021-01-19 10:35 UTC, sasjo requested changes
We should add to ASSESS and not ADOPT.

Also, please include a list of things to assess, for example maybe how efficient it is, how we can handle false-positives and how we can enforce it in workflows?

2021-01-21 08:54 UTC, l0kal requested changes
Great description now, but can you please add a list of things we should assess regarding Trivy. It will help with having tangible arguments going into TRIAL and ADOPT.

2021-01-21 08:54 UTC, l0kal commented on radar/infrastructure_ci_cd/trivy.yaml
> +  It is very fast and has almost the same sthength as GCP Container Registry Scanning service,
Strenght*? :)

2021-01-29 09:32 UTC, sasjo approved these changes

2021-02-04 10:57 UTC, l0kal approved these changes

2021-02-04 13:53 UTC, merged