feat: Trial React Native Web
extenda/tech-radar pull request #211
Opened 2021-04-30 12:40 UTC by vadimb

2021-04-30 12:58 UTC, vadimb commented
Please don't merge yet as this will be discussed in the chapter frontend.

2021-05-05 06:27 UTC, sasjo requested changes
Introduce this as an assess instead of trial.

2021-05-06 13:04 UTC, sasjo commented on radar/dev/reactnative_web.yaml
> +    ring: TRIAL
Change the `ring` to ASSESS.

2021-05-06 18:48 UTC, sirenko7 approved these changes

2021-05-06 20:36 UTC, l0kal requested changes
Please fix the typos and wording. I have attached a corrected text. Please advise.

2021-05-06 20:36 UTC, l0kal commented on radar/dev/reactnative_web.yaml
> +  where maintaing a separate web interface adds more complexity for the team and time to market.
```
Allows having a React Native app that runs in the browser. Going forward, the trend of having a codebase
  that runs in the browser besides JS is just about to increase with the help of WebAssembly(Flutter Web, Blazor)
  even though RN Web isn't based on it.

  Of course, this is not for all types of apps but where we need to support more platforms.

  We'd like to assess this for Cloud POS and Attendant App where we need web support besides Android/iOS and
  where maintaining a separate web interface adds more complexity for the team and time to market.
```

2021-05-20 08:12 UTC, sasjo approved these changes

2021-05-20 08:14 UTC, merged